baseURL: 'https://kuchida1981.github.io/'
locale: 'ja-JP'
title: 'U-REI.com'
theme: papermod
enableRobotsTXT: true
copyright: © 2023-2026 Kosuke Uchida
publishDir: docs
canonifyURLs: true

taxonomies:
  tag: tags
  category: categories
  author: author

related:
  threshold: 20
  includeNewer: true
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 20

Params:
  googleAnalyticsID: "G-QSVPG0XQ59"
  author: Kosuke Uchida
  description: "バックエンド・インフラを中心に活動するフリーランスエンジニアの個人ブログ。技術的な試行錯誤の記録から日々のニュース、ときにフィクションまで。"
  DateFormat: 2006-01-02 15:04
  defaultTheme: auto
  hideSummary: false
  ShowBreadCrumbs: true

  profileMode:
    enabled: true
    subtitle: new world order
    imageUrl: profile.png
    imageTitle: profile

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: achievements
      name: "実績"
      url: /achievements/
      weight: 3
    - identifier: playground
      name: Playground
      url: /playground/
      weight: 5
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: contact
      name: Contact
      url: https://docs.google.com/forms/d/e/1FAIpQLSeiyFY03faZAgA207PlfcNLV2Xp357oJFboGB9GIT6hVpByhw/viewform?usp=publish-editor
      weight: 20
      params:
        target: "_blank"
