version: '3'
services:
  hugo:
    build:
      context: .
      args:
        - HUGO_VERSION=${HUGO_VERSION:-0.111.3}
        - ARCH=${ARCH:-amd64}
    ports:
      - ${HUGO_BASE_PORT:-1313}:1313
    volumes:
      - "./:/work"
    working_dir: "/work"
    command:
      - "server"
      - "--bind"
      - "0.0.0.0"
      - "-D"
      - "-F"
      - "--port"
      - "1313"
      - "--appendPort=false"
      - "--baseURL"
      - "http://${HUGO_BASE_HOST:-localhost}:${HUGO_BASE_PORT:-1313}/"
      - "--liveReloadPort=${HUGO_BASE_PORT:-1313}"
