version: '3'
services:
  hugo:
    build: .
    ports:
      - 1313:1313
    volumes:
      - "./:/work"
    working_dir: "/work"
    command:
      - "server"
      - "--bind"
      - "0.0.0.0"
      - "-D"
      - "-F"
      - "--baseURL"
      - "${HUGO_BASE_URL:-http://localhost}"
      - "--port"
      - "${HUGO_PORT:-1313}"
